name: Isabelo Design
favicon: null
layout_spectrum: 0.10263
typography_spectrum: 0.46875
title: Interior Designer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dac4b9'
    - '#000000'
    - '#293b45'
    - '#967c6b'
  brandStrength: 0.875
  lightness: 0.8125
  saturation: 0.9103176759090275
  rhythmicContrast: 0.25
purpose: []
